
- name: get local hostname

  block:

  - local_action: command hostname
    register: hostname_cat


  - name: set local_hostname
    set_fact:
      local_hostname: "{{ _hostname_cat.stdout }}"



